name: Mirror Branch to GitLab

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter the branch name to mirror'
        required: true
        type: string

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Push selected branch to GitLab
        run: |
          git remote add gitlab \
            https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@codevault.cyntexa.com/samyakjain1/tryfinal.git

          git push gitlab HEAD:${{ inputs.branch }} --force